# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
null_vector_with_one = np.zeros(10)
null_vector_with_one[4] = 1
null_vector_with_one

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
vector_10_to_49 = np.arange(10, 50)
vector_10_to_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [7]:
reversed_vector = vector_10_to_49[::-1]
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [9]:
non_zero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
non_zero_indices

(array([0, 1, 4]),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [20]:
random_3x3x3_array = np.random.random((3, 3, 3))
random_3x3x3_array

array([[[0.18146781, 0.30935316, 0.47957628],
        [0.7205524 , 0.08115666, 0.24914155],
        [0.75116878, 0.88060547, 0.06263866]],

       [[0.00995384, 0.11307919, 0.90260334],
        [0.81405656, 0.92952934, 0.73436775],
        [0.94874948, 0.54820751, 0.93160654]],

       [[0.38031943, 0.98612393, 0.15898807],
        [0.00302038, 0.92396372, 0.50168294],
        [0.95061723, 0.63007427, 0.47486212]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
random_10x10_array = np.random.random((10, 10))
min_value = random_10x10_array.min()
max_value = random_10x10_array.max()
print(random_10x10_array)
print(min_value)
print(max_value)

[[0.42317495 0.16229643 0.14042756 0.52607554 0.10142234 0.39411413
  0.06289332 0.37963076 0.00986981 0.7959918 ]
 [0.9185006  0.14797825 0.71561906 0.79057724 0.71369048 0.9982937
  0.24534247 0.02718512 0.15888784 0.15080841]
 [0.19309319 0.01998624 0.12707885 0.18027651 0.8342255  0.16922146
  0.10611169 0.9291797  0.78269949 0.72231864]
 [0.44244213 0.82562835 0.22589328 0.86588714 0.1007761  0.38182245
  0.06093263 0.13665665 0.75320058 0.05211195]
 [0.27907679 0.92630693 0.70657109 0.01233005 0.51244683 0.12755623
  0.57248901 0.30255105 0.27636519 0.49181673]
 [0.96919558 0.42885758 0.31943134 0.72407922 0.10657809 0.24432973
  0.44487716 0.15155971 0.19997059 0.03548477]
 [0.23874067 0.7373644  0.59714113 0.51158286 0.75167416 0.84946219
  0.52279507 0.24754718 0.80728701 0.81519986]
 [0.69808188 0.00932608 0.88696533 0.82996596 0.81423254 0.48703548
  0.76987557 0.1348014  0.58775311 0.32241655]
 [0.69000185 0.2480611  0.36438035 0.02192304 0.78574887 0.55063034
  0.47405282 

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
mean_value

0.48253078888490913

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [28]:
bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0
bordered_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
diagonal_matrix = np.diag(1 + np.arange(4), k=-1)
diagonal_matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [31]:
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
normalized_matrix

array([[0.65460277, 0.90361687, 1.        , 0.71976918, 0.84785091],
       [0.53941519, 0.74841019, 0.9469362 , 0.64093341, 0.88229773],
       [0.85687484, 0.32611397, 0.66025773, 0.34839439, 0.28346455],
       [0.90856602, 0.99410288, 0.64205864, 0.52902094, 0.44545928],
       [0.85529288, 0.01317254, 0.35976695, 0.        , 0.10624076]])

#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [32]:
array_to_negate = np.arange(11)
array_to_negate[(array_to_negate >= 3) & (array_to_negate <= 8)] *= -1
array_to_negate

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 18. How to round away from zero a float array ? (★☆☆)

<generator object <genexpr> at 0x106576810>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 19. Find common values between two arrays? (★☆☆)

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [36]:
generator = (x for x in range(10))
print(generator)
array_from_generator = np.fromiter(generator, dtype=int)
array_from_generator

<generator object <genexpr> at 0x10770b1d0>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [37]:
vector_excluded_values = np.linspace(0, 1, 12)[1:-1]
vector_excluded_values

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [39]:
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
sorted_vector

array([0.05956383, 0.11850465, 0.12471703, 0.17212753, 0.2231223 ,
       0.45463129, 0.64564773, 0.76355896, 0.8887864 , 0.91100341])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [40]:
random_vector = np.random.random(10)
random_vector[random_vector.argmax()] = 0
random_vector

array([0.39505938, 0.3841681 , 0.33852341, 0.88642264, 0.29625851,
       0.        , 0.86893379, 0.75113585, 0.53813044, 0.65859278])

#### 26. Find the closest value to random element in a vector? (★★☆)

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

#### 28. Sort an array by the nth column? (★★☆)

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [41]:
original_vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(original_vector) * 4 - 3)
new_vector[::4] = original_vector
new_vector

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 31. Swap two rows of an array? (★★★)

In [42]:
matrix_to_swap_rows = np.arange(9).reshape(3, 3)
matrix_to_swap_rows[[0, 1]] = matrix_to_swap_rows[[1, 0]]
matrix_to_swap_rows

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 32. How to negate a boolean value inside an array? (★★★)

In [43]:
boolean_array = np.array([True, False, True])
negated_boolean_array = np.logical_not(boolean_array)
negated_boolean_array

array([False,  True, False])

#### 33. Find the most frequent value in an array?

In [44]:
array_to_find_mode = np.array([1, 2, 3, 2, 4, 2, 5, 2])
most_frequent_value = np.bincount(array_to_find_mode).argmax()
most_frequent_value

2

#### 34. Get the n largest values of an array (★★★)

In [46]:
array_to_get_largest_values = np.array([1, 5, 3, 8, 2, 7])
n_largest_values = np.partition(array_to_get_largest_values, -3)[-3:]
n_largest_values

array([5, 7, 8])

#### 35. Extract unique rows from a two dimensional array? (★★★)

In [47]:
two_dim_array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])
unique_rows = np.unique(two_dim_array, axis=0)
unique_rows

array([[1, 2, 3],
       [4, 5, 6]])